name: mybt-signin

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  signin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run signin
        env:
          MYBT_USERNAME: ${{ secrets.MYBT_USERNAME }}
          MYBT_PASSWORD: ${{ secrets.MYBT_PASSWORD }}
        run: python signin.py
